config/routes.rb
GemBreakfastSpots::Application.routes.draw do
  resources :spots
  root 'spots#index'

  

end

app/models/spot.rb
class Spot
  include Mongoid::Document
  field :latitude, type: String
  field :longitude, type: String
  field :address, type: String
  field :description, type: String
  field :title, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @spot }
      else
        format.html { render action: 'new' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Map of Brentwood for Julie!</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Add", class: "btn btn-info" %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<div class="container-fluid">
  <div class="row">
	    <div class="col-md-3"></div>
	    <div class="col-md-6">
	    	<h1>Editing spot</h1>

			<%= render 'form' %>

			<%= link_to 'Show', @spot %> |
			<%= link_to 'Back', spots_path %>
		</div>
		<div class="col-md-3"></div>
  	</div>
</div>

app/views/spots/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="container">
  <h1>Hi Julie!</h1>
   <br><h2>Today we had fun with the Google Maps API</h2>
  
<div style='width: 800px;'>
  <div id="multi_overlays" style='width: 800px; height: 400px;'></div>
</div>


  <script type="text/javascript">
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'multi_overlays'}}, function(){


  var circles = handler.addCircles(
    [{ lat: 34.052525, lng: -118.47, radius: 50 }],
    { strokeColor: '#FF0000'}
  );

  var polylines = handler.addPolylines(
    [
      [
        {lat: 34.047, lng: -118.47},
        {lat: 34.050525, lng: -118.47}
      ]
    ],
    { strokeColor: '#FF0000'}
  );

  var polylines = handler.addPolylines(
    [
      [
        {lat: 34.047, lng: -118.45},
        {lat: 34.053, lng: -118.45}
      ]
    ],
    { strokeColor: '#FF0000'}
  );

    var polylines = handler.addPolylines(
    [
      [
        {lat: 34.047, lng: -118.45},
        {lat: 34.047, lng: -118.455}
      ]
    ],
    { strokeColor: '#FF0000'}
  );

    var polylines = handler.addPolylines(
    [
      [
        {lat: 34.047, lng: -118.455},
        {lat: 34.053, lng: -118.455}
      ]
    ],
    { strokeColor: '#FF0000'}
  );


  var polygons = handler.addPolygons(
    [
      [ 
        {lat:  34.052, lng:  -118.466}, { lat: 34.055, lng:  -118.465},          
        {lat:  34.0525, lng:  -118.463}, { lat: 34.055, lng:  -118.461},  
        {lat:  34.052, lng:  -118.460}, { lat: 34.047, lng:  -118.463},
      ]
    ],
    { strokeColor: '#FF0000'}
  );

  handler.bounds.extendWith(polylines);
  handler.bounds.extendWith(polygons);
  handler.bounds.extendWith(circles);
  handler.fitMapToBounds();
});

   </script>
 </div>

app/views/spots/new.html.erb
<div class="container-fluid">
  <div class="row">
	    <div class="col-md-3"></div>
	    <div class="col-md-6">
	    	<h1>New spot</h1>

			<%= render 'form' %>

			<%= link_to 'Back', spots_path %>
		</div>
		<div class="col-md-3"></div>
  	</div>
</div>

app/views/spots/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 profile">
    <p id="notice"><%= notice %></p>

    <p class="lead">
      <strong>Latitude:</strong>
      <%= @spot.latitude %>
    </p>

    <p class="lead">
      <strong>Longitude:</strong>
      <%= @spot.longitude %>
    </p>

    <p class="lead">
      <strong>Address:</strong>
      <%= @spot.address %>
    </p>

    <p class="lead">
      <strong>Description:</strong>
      <%= @spot.description %>
    </p>

    <p class="lead">
      <strong>Title:</strong>
      <%= @spot.title %>
    </p>

    <p class="lead">
    <%= link_to 'Edit', edit_spot_path(@spot) %> |
    <%= link_to 'Back', spots_path %>
    </p>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>